definitions:
  Site:
    properties:
      name:
        type: string
      title:
        type: integer
  Error:
    properties:
      error:
        name: string
        example: Example error

/current-site:
  get:
    tags:
      - Access
    summary: Sites
    description: Get he current site set for the logged user
    produces:
      -  application/json
    responses:
      '200':
        description: The current site
        schema:
          $ref: '#/definitions/Site'
      '204':
        description: No current site selected
      '403':
        description: No session
        schema:
          $ref: '#/definitions/Error'

/switch-site:
  post:
    tags:
      - Access
    summary: Sites
    description: Switch the site for the logged user
    produces:
      -  application/json
    responses:
      '200':
        description: Success
        schema:
          $ref: '#/definitions/Site'
      '403':
        description: No session
        schema:
          $ref: '#/definitions/Error'

/site:
  get:
    tags:
      - Access
    summary: Sites
    description: Get sites available for the logged user
    produces:
      -  application/json
    responses:
      '200':
        description: Success
        schema:
          $ref: '#/definitions/Site'
      '403':
        description: No session
        schema:
          $ref: '#/definitions/Error'
