definitions:
  Menu:
    properties:
      name:
        type: string
      label:
        type: integer
  Error:
    properties:
      error:
        name: string
        example: Example error

/menu:
  get:
    tags:
      - Menu
    summary: Menu
    description: Get the menu for the logged user
    produces:
      - application/json
    responses:
      '200':
        description: Success
        schema:
          $ref: '#/definitions/Menu'
      '403':
        description: No session
        schema:
          $ref: '#/definitions/Error'
