/api/logout:
  post:
    tags:
      - Authorization
    summary: Logout
    description: Ends a session in the system
    security:
      - bearerAuth: []
    produces:
      -  empty
    consumes:
      -  application/json
    parameters:
    responses:
      '204':
        description: Success
      '403':
        description: No session
        schema:
          $ref: '#/definitions/Error'
      '500':
        description: Error
        schema:
          $ref: '#/definitions/Error'
