components:
  schemas:
    Page:
      properties:
        uuid:
          type: UUID
        isEnabled:
          type: boolean
        name:
          type: string
        label:
          type: integer
        isTranslatable:
          type: boolean
        translationContext:
          type: string
        title:
          type: string
        content:
          type: string

    Error:
      properties:
        error:
          name: string
          example: Example error

/page:
  get:
    tags:
      - Page
    summary: Page
    description: Get the page for the given name
    produces:
      - application/json
    responses:
      '200':
        description: Success
        schema:
          $ref: '#/components/schemas/Page'
      '403':
        description: No session
        schema:
          $ref: '#/components/schemas/Error'
